"""Added kratos id to user model

Revision ID: 3a9b408c0f14
Revises: 7ecc7dd06578
Create Date: 2026-05-21 18:56:55.929140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9b408c0f14'
down_revision: Union[str, None] = '7ecc7dd06578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kratos_id', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'users', ['kratos_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'kratos_id')
    # ### end Alembic commands ###
