"""Added status to user model

Revision ID: 764863b3ef5e
Revises: 8485ce4ab419
Create Date: 2026-03-28 11:10:27.020001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764863b3ef5e'
down_revision: Union[str, None] = '8485ce4ab419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userstatus AS ENUM ('ACTIVE', 'DELETED', 'PENDING')")
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'PENDING', name='userstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.execute("DROP TYPE userstatus")
# ### end Alembic commands ###
