"""Existing models updated and Counter model added

Revision ID: 7ecc7dd06578
Revises: 764863b3ef5e
Create Date: 2026-04-04 10:58:20.902541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '7ecc7dd06578'
down_revision: Union[str, None] = '764863b3ef5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###

	op.drop_table('subsessions')
	op.drop_table('sessions')
	op.drop_table('users')

	op.create_table('counters',
	                sa.Column('name', sa.String(length=50), nullable=False),
	                sa.Column('value', sa.Integer(), nullable=False),
	                sa.Column('description', sa.String(length=255), nullable=True),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.PrimaryKeyConstraint('name')
	                )

	op.create_table('users',
	                sa.Column('id', sa.UUID(), nullable=False),
	                sa.Column('code', sa.String(length=20), nullable=False),
	                sa.Column('first_name', sa.String(length=50), nullable=False),
	                sa.Column('last_name', sa.String(length=50), nullable=False),
	                sa.Column('email', sa.String(length=120), nullable=False),
	                sa.Column('status', ENUM('ACTIVE', 'DELETED', 'PENDING', name='userstatus', create_type=False), nullable=False),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.PrimaryKeyConstraint('id'),
	                sa.UniqueConstraint('code'),
	                sa.UniqueConstraint('email')
	                )

	op.create_table('sessions',
	                sa.Column('id', sa.UUID(), nullable=False),
	                sa.Column('code', sa.String(length=20), nullable=False),
	                sa.Column('activity', sa.String(length=50), nullable=False),
	                sa.Column('user_id', sa.UUID(), nullable=True),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
	                sa.PrimaryKeyConstraint('id'),
	                sa.UniqueConstraint('code'),
	                )
	op.create_table('subsessions',
	                sa.Column('id', sa.UUID(), nullable=False),
	                sa.Column('code', sa.String(length=20), nullable=False),
	                sa.Column('name', sa.String(length=50), nullable=False),
	                sa.Column('session_id', sa.UUID(), nullable=True),
	                sa.Column('duration', sa.Integer(), nullable=False),
	                sa.Column('break_at_end', sa.Integer(), nullable=True),
	                sa.Column('order_index', sa.Integer(), nullable=False),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
	                sa.PrimaryKeyConstraint('id'),
	                sa.UniqueConstraint('code'),
	                )

	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###

	# Drop tables in reverse order (dependents first)
	op.drop_table('subsessions')
	op.drop_table('sessions')
	op.drop_table('users')
	op.drop_table('counters')

	# Recreate the old structure (without UUID, without code fields)
	op.create_table('users',
	                sa.Column('id', sa.String(length=20), nullable=False),
	                sa.Column('first_name', sa.String(length=50), nullable=False),
	                sa.Column('last_name', sa.String(length=50), nullable=False),
	                sa.Column('email', sa.String(length=120), nullable=False),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.PrimaryKeyConstraint('id'),
	                sa.UniqueConstraint('email')
	                )

	op.create_table('sessions',
	                sa.Column('id', sa.String(length=20), nullable=False),
	                sa.Column('activity', sa.String(length=50), nullable=False),
	                sa.Column('user_id', sa.String(length=20), nullable=True),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
	                sa.PrimaryKeyConstraint('id')
	                )

	op.create_table('subsessions',
	                sa.Column('id', sa.String(length=20), nullable=False),
	                sa.Column('name', sa.String(length=50), nullable=False),
	                sa.Column('session_id', sa.String(length=20), nullable=True),
	                sa.Column('duration', sa.Integer(), nullable=False),
	                sa.Column('break_at_end', sa.Integer(), nullable=True),
	                sa.Column('order_index', sa.Integer(), nullable=False),
	                sa.Column('created_at', sa.DateTime(), nullable=True),
	                sa.Column('updated_at', sa.DateTime(), nullable=True),
	                sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
	                sa.PrimaryKeyConstraint('id')
	                )

# ### end Alembic commands ###
