
services:
#  database_dev:
#    image: postgres:18
#    container_name: sessionbloom_dev_database
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_dev_data:/var/lib/postgresql
#    restart: unless-stopped

  backend_dev:

    container_name: dev_python_api
    build: .
    ports:
      - "5001:5000" # In container 5000, from local machine 5001 as address
    environment:
      - DATABASE_URL=${REMOTE_URL}
      - FLASK_APP=app:create_app
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
#    depends_on:
#      - database_dev


#volumes:
#  postgres_dev_data: